### ISSUE TITLE
PHP Fatal Error Uncaught TypeError: in_array() - Seem to be occurring after update to latest version (3.2.0)

### ISSUE THREAD

**Issue by rhughesiu** [caseproof/members#71]
PHP Fatal error Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in /groups/tmsdev/web/wp-content/plugins/members/admin/functions-admin.php:258
Stack trace:
#0 /groups/tmsdev/web/wp-content/plugins/members/admin/functions-admin.php(258): in_array()
#1 /groups/tmsdev/web/wp-content/plugins/members/admin/class-notifications.php(372): members_is_admin_page()
#2 /groups/tmsdev/web/wp-includes/class-wp-hook.php(303): Members\Admin\Notifications->enqueues()
#3 /groups/tmsdev/web/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#4 /groups/tmsdev/web/wp-includes/plugin.php(470): WP_Hook->do_action()
#5 /groups/tmsdev/web/wp-admin/admin-header.php(102): do_action()
#6 /groups/tmsdev/web/wp-admin/update-core.php(1016): require_once('...')
#7 /groups/tmsdev/web/wp-admin/network/update-core.php(13): require('...')
#8 {main}
thrown in /groups/tmsdev/web/wp-content/plugins/members/admin/functions-admin.php on line 258

**Comment by rhughesiu** [comment]
@renventura - That seemed to resolve the issue. Thank you so much for remedying that and with such a quick turnaround as well.

**Comment by renventura** [comment]
You're welcome @rhughesiu. Thanks for the report.
